### ISSUE TITLE
Krista's to-do list

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#3]
- [x] orient myself and interns to FastField (accounts, download app, etc.)
- [x] define system for processing FastField forms + photos (#8)
- [x] define list of checks for continuous integration (#2 ) 
- [x] plan/initiate updating of metadata (#7, #9) 
- [x] clarify relationship between the two mortality repos/ repo sections (this one + https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/tree/master/tree_mortality) (#4)
- [x] EAB census update (#5)

**Comment by teixeirak** [comment]
I've opened issues for all of these/ got everything started, so closing this.
