### ISSUE TITLE
Resolving issues in the data

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/SCBImortality#54]
This is the running list of things to resolve, starting with the latest census:

- [x] resolve duplicates - see #48 
- [ ] resolve warnings:
  - [ ] trees that are alive but were previously dead - see #59
    - [x] @ValentineHerr will make a status history of those to see if we can figure out the "truth"
  - [ ] DBH dead suspicious - see #55
    - [ ] @ValentineHerr will make dbh history plots for those  and see if we need to worry or not 
- [ ] resolve errors that can be automatically fixed
  - [ ] unhealthy but wrong status-  **rule**: 
  - [ ] wounded level but wrong status or FAD - **rule**:

**Comment by ValentineHerr** [comment]
for errors that can be automatically fixed --> add rows to [this file](https://github.com/SCBI-ForestGEO/SCBImortality/blob/df08e9a47ab6518cbd541d81182e745f45541ac8/raw_data/consitent_fixes.csv)

@teixeirak, just tagging you here as we need to define the rules for the errors and you may get to it before I do.

**Comment by ValentineHerr** [comment]
also see #65
