### ISSUE TITLE
cleaning TODO list to unify all years

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/SCBImortality#63]
- [x] standardize status (remove spaces and "no sampled")
- [x] combine 2017's `eabf` columns into one **--> was already combined in EABF column**
- [x] combine 2014-2020's `fad` columns into one 
- [x] standardize the separators in `eabf` and `fad` columns
- [x] figure out the species = NA in 2021
- [x] calculate (or retrieve) `gx`, `gy`, `lx`, `ly` in all years
- [x] translate 2021 `percent_of_crown_intact` to `score.crown.intact` (originally `perc.crown` score 1-5)
- [x] translate 2021 `percent_of_crown_living` to `score.crown.living` (originally `DF` score 1-5)
- [x] create a file for "manual fixes" and implement them when bringing in the data
-  figure out species issues looking at when `eabf` is recorded for none fraxinus or chvi species (see #47) **not dealing with this now**

**Comment by ValentineHerr** [comment]
yes! closing this.
