### ISSUE TITLE
Prepare for start of 2022 census

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/SCBImortality#69]
@emacmonigle , @jenajordan , @jess-shue , @ValentineHerr , 

The 2022 mortality census will start May 18, so we want to be all set up by then.  I'm opening this issue to be a master list of things that need to happen before then, and we can open separate issues for items that require more work.

*Running list:*
- [ ] operational
  - [x] #73
  - [x] prepare 2022 FastField form (@jess-shue , with input from @ValentineHerr )
  - [x] prepare 2022 maps (@jess-shue )
  - [x] #70
  - [x] get Erin (@emacmonigle ) on board with GitHub and CI system 
  - [x] set up Erin's badge access (forms sent 4/27)
- [x] fixes to CI system
  - [x] switch suspicious DBH from warning to error #55 
- [ ] fixes to data
  - [ ] correct status of trees found live when coring #60
  - [ ] correct hickories identified as ash #47 
- [ ] prepare/update documentation
  - [x] #62 
  - [x] #64
  - [ ] #7
- [ ] if necessary, set up system for ground-truthing lidar data (@ebennb ;  issue #66 )

**Comment by jess-shue** [comment]
@teixeirak I'm hoping to have the FastField Forms app updated this week by adding the status of the trees from last year's mortality survey.
For the maps, previously they were very simple with points by size and a tag number. Do you want them re-made, maybe designating last year's status with a color, or will those maps work again?  [This](https://github.com/SCBI-ForestGEO/SCBImortality/tree/main/doc/maps) is the location of the maps currently.

**Comment by teixeirak** [comment]
It would be fantastic to color by last year's status if you can do it easily, but I don't think it's critical.

**Comment by teixeirak** [comment]
hmmm.... in theory there shouldn't be any NA's, right? Any idea what's going on there?

**Comment by ValentineHerr** [comment]
NA are for previously dead or missed trees. Also for trees that are <10cm (which are remnant of the first mort census, I think)

**Comment by jess-shue** [comment]
I thought last year we removed trees <10 cm unless they were Fraxinus or Chionanthus from the data for FastField Forms. So, should the trees <10 cm that aren't those two species be removed again?



<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



stem not sampled,   info automatically filled from previous year info
--




</body>

</html>


<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jessh/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



stem not sampled,   info automatically filled from previous year info
--




</body>

</html>

**Comment by teixeirak** [comment]
Hmmm... that would mean some hole in the CI system. It got very complicated with the changing census lists, so I'd suspect it's linked to that.

**Comment by jess-shue** [comment]
The issues last year stemmed from trying to use the [mortality data vs. census data](https://github.com/SCBI-ForestGEO/SCBImortality/issues/31) in the app and my confusion with some of the columns. I'm going to follow Valentine's suggestion again from that issue.

**Comment by ValentineHerr** [comment]
I need to rework the filling of "overall".... right now I am getting H for everybody and I don't understand why yet.

**Comment by teixeirak** [comment]
@jess-shue , are we all set with fast field setup for this year's census?

**Comment by teixeirak** [comment]
(there are a couple fixes to the data that I was hoping to make ahead of the census, but think we're out of time for that now.)

**Comment by jess-shue** [comment]
@teixeirak Hi Krista, I did use the 2021 mortality data to build the app. I'm testing things today to make sure the new version is fully functional. If you have some changes I should still be able to add them.

**Comment by teixeirak** [comment]
Awesome, thank you!
